/**
 * Turning generated scales into the two shippable artefacts.
 *
 * `lattice.css` is what a consumer imports; `tokens.json` is the machine-readable
 * form, in the Design Tokens Community Group format.
 *
 * This module emits the **primitive tier** only. The semantic tier — step aliases
 * and role aliases — and the nested-mode behaviour that depends on it land in #6.
 */

import { MODES, STEPS, type Mode } from '../config/lightness.js'
import { SCALE_JOBS, STEP_JOBS } from '../config/steps.js'
import type { Scale, Swatch } from './scale.js'

/**
 * The published DTCG schema. The format module notes that a schema is still being
 * explored, but this one is live and versioned, so the artefact points at it.
 */
export const DTCG_SCHEMA = 'https://www.designtokens.org/schemas/2025.10/format.json'

/**
 * Decimal places kept in an emitted colour.
 *
 * Not cosmetic. At three places — the precision the spec's own tables print — 21
 * of the 120 generated colours re-emit as a different byte, and at five places two
 * still do: the solved success steps, whose lightness comes off a binary search
 * rather than the curve. Six round-trips all 120 exactly, so the colour a browser
 * computes is the colour whose contrast was verified.
 */
const PLACES = 6

function trim(value: number): string {
  // toFixed then back through Number drops trailing zeros, so a hue stays `305`
  // rather than becoming `305.000000`.
  return String(Number(value.toFixed(PLACES)))
}

/** A swatch as a CSS `oklch()` value. */
export function formatOklch(swatch: Pick<Swatch, 'l' | 'c' | 'h'>): string {
  return `oklch(${trim(swatch.l)} ${trim(swatch.c)} ${trim(swatch.h)})`
}

const customProperty = (scale: Scale, swatch: Swatch): string =>
  `  --lat-${scale.name}-${swatch.step}: ${formatOklch(swatch)};`

function block(scales: readonly Scale[], mode: Mode): string {
  return scales
    .filter((scale) => scale.mode === mode)
    .map((scale) => scale.steps.map((swatch) => customProperty(scale, swatch)).join('\n'))
    .join('\n\n')
}

/**
 * The stylesheet.
 *
 * Values ship as `oklch()` alone, with no hex companion. A second declaration
 * would not be a fallback: custom property values are parsed as a raw token
 * stream, so a browser that cannot resolve `oklch()` still accepts the
 * declaration and only fails later, at `var()` time. Whichever declaration comes
 * last simply wins. A genuine fallback would need an `@supports` block
 * duplicating every value, and the verified hex is carried in `tokens.json`
 * instead, where DTCG defines a field for exactly that.
 *
 * Every colour here is already fitted into sRGB, so `oklch()` buys precision
 * rather than gamut. Wide-gamut output is a stated non-goal for v1.
 */
export function emitCss(scales: readonly Scale[]): string {
  const [light, dark] = MODES

  return `/* Lattice tokens — generated by generate/emit.ts. Do not edit by hand. */
/* Primitive tier: ${scales.length / MODES.length} scales x ${STEPS} steps, both modes. */

:root,
[data-lat-theme='${light}'] {
${block(scales, light!)}
}

[data-lat-theme='${dark}'] {
${block(scales, dark!)}
}

/* The OS preference supplies the default and an explicit stamp overrides it in
   both directions, so this comes after the attribute rules and excludes an
   element that has asked for light. */
@media (prefers-color-scheme: dark) {
  :root:not([data-lat-theme='${light}']) {
${block(scales, dark!)
    .split('\n')
    .map((line) => (line ? `  ${line}` : line))
    .join('\n')}
  }
}
`
}

/** A DTCG colour token. */
export interface ColorToken {
  readonly $type: 'color'
  readonly $description?: string
  readonly $value: {
    readonly colorSpace: 'oklch'
    /** `[lightness, chroma, hue]`. */
    readonly components: readonly [number, number, number]
    readonly alpha: number
    /** The sRGB fallback, which DTCG defines for this purpose. */
    readonly hex: string
  }
}

export interface DesignTokens {
  readonly $schema: string
  readonly $description: string
  readonly [mode: string]: unknown
}

function token(swatch: Swatch): ColorToken {
  return {
    $type: 'color',
    $description: STEP_JOBS[swatch.step - 1] ?? `step ${swatch.step}`,
    $value: {
      colorSpace: 'oklch',
      components: [
        Number(swatch.l.toFixed(PLACES)),
        Number(swatch.c.toFixed(PLACES)),
        Number(swatch.h.toFixed(PLACES))
      ],
      alpha: 1,
      hex: swatch.hex
    }
  }
}

/**
 * The machine-readable artefact.
 *
 * Modes are top-level groups because DTCG defines no mechanism for themes — that
 * gap is acknowledged in the format module itself, so any shape here is a local
 * convention. Groups keep the same names the CSS uses, so a token's path and its
 * custom property are mechanically related: `light.accent.9` is
 * `--lat-accent-9` under the light theme.
 */
export function emitTokens(scales: readonly Scale[]): DesignTokens {
  const modes: Record<string, unknown> = {}

  for (const mode of MODES) {
    const group: Record<string, unknown> = {
      $description: `Primitive colour scales, ${mode} mode. Generated — never hand-edited.`
    }

    for (const scale of scales.filter((entry) => entry.mode === mode)) {
      const steps: Record<string, ColorToken> = {}

      for (const swatch of scale.steps) {
        steps[String(swatch.step)] = token(swatch)
      }

      group[scale.name] = {
        $description: SCALE_JOBS[scale.name] ?? scale.name,
        ...steps
      }
    }

    modes[mode] = group
  }

  return {
    $schema: DTCG_SCHEMA,
    $description:
      'Lattice primitive colour tokens. Generated in OKLCH from a config whose ' +
      'contrast contracts fail the build. Do not edit by hand.',
    ...modes
  }
}
